
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


 
 
 
STATE_MAGE_CHASERCLUSTER         <- 242    
STATE_MAGE_AVATARDANCE         <- 243    
STATE_MAGE_SWINGEXX          <- 244    
STATE_MAGE_AVATAR          <- 245    
STATE_MAGE_RETURNTOBM         <- 246    
STATE_MAGE_QUASAREXPLOSION        <- 247    
STATE_MAGE_DRAGONDANCE         <- 248    
STATE_MAGE_ELEMENTALCURTAIN        <- 249    
STATE_MAGE_ELEMENTALQUAKE        <- 250    
STATE_MAGE_CRYSTALOFOVERMIND        <- 251    
STATE_MAGE_THEGATE          <- 252    
STATE_MAGE_SESTOELEMENTO         <- 253    
STATE_MAGE_ELECTRICRABBIT        <- 131    
STATE_MAGE_JACKFROSTICEWATER        <- 132    
STATE_MAGE_LOLLIPOPCRUSH         <- 133    
STATE_MAGE_UROBOROS          <- 134    
STATE_MAGE_MOONSHADOW         <- 135    
STATE_MAGE_SUMMONKRUTA         <- 136    
STATE_MAGE_REPEATEDSMASHOFRAGE       <- 137    
STATE_MAGE_SUMMONHEILROM         <- 138    
STATE_MAGE_SUMMONRAMOS         <- 139    
STATE_MAGE_BUGFALL          <- 126    


 
SKILL_ZHAN_LING_QIAN_NENG			<- 32
SKILL_homunculus					<- 33
 
SKILL_MAGE_CHASERCLUSTER         <- 242    
SKILL_MAGE_AVATARDANCE         <- 243    
SKILL_MAGE_SWINGEXX          <- 244    
SKILL_MAGE_AVATAR          <- 245    
SKILL_MAGE_RETURNTOBM         <- 246    
SKILL_MAGE_QUASAREXPLOSION        <- 247    
SKILL_MAGE_DRAGONDANCE         <- 248    
SKILL_MAGE_ELEMENTALCURTAIN        <- 249    
SKILL_MAGE_ELEMENTALQUAKE        <- 250    
SKILL_MAGE_CRYSTALOFOVERMIND        <- 251    
SKILL_MAGE_THEGATE          <- 252    
SKILL_MAGE_SESTOELEMENTO         <- 253    
SKILL_MAGE_ELECTRICRABBIT        <- 131    
SKILL_MAGE_JACKFROSTICEWATER        <- 132    
SKILL_MAGE_LOLLIPOPCRUSH         <- 133    
SKILL_MAGE_UROBOROS          <- 134    
SKILL_MAGE_MOONSHADOW         <- 135    
SKILL_MAGE_SUMMONKRUTA         <- 136    
SKILL_MAGE_REPEATEDSMASHOFRAGE       <- 137    
SKILL_MAGE_SUMMONHEILROM         <- 138    
SKILL_MAGE_SUMMONRAMOS         <- 139    
SKILL_MAGE_BUGFALL          <- 126    


SKILL_MAGE_COMMINTERRUPT <- 254
 
 
CUSTOM_ANI_MAGE_CHASERCLUSTERBODYSTART_09    <- 82   
CUSTOM_ANI_MAGE_CHASERCLUSTERBODYEND_06     <- 83   
CUSTOM_ANI_MAGE_AVATARDANCE_A       <- 84   
CUSTOM_ANI_MAGE_AVATARDANCE_B       <- 85   
CUSTOM_ANI_MAGE_AVATARDANCE_C       <- 86   
CUSTOM_ANI_MAGE_AVATARDANCE_D       <- 87   
CUSTOM_ANI_MAGE_AVATARDANCE_E01       <- 88   
CUSTOM_ANI_MAGE_AVATARDANCE_E02       <- 89   
CUSTOM_ANI_MAGE_AVATARDANCE_F01       <- 90   
CUSTOM_ANI_MAGE_AVATARDANCE_F02       <- 91   
CUSTOM_ANI_MAGE_NNNEWSWING_BODY       <- 92   
CUSTOM_ANI_MAGE_AVATARREADYA_BODY      <- 93   
CUSTOM_ANI_MAGE_AVATARFINISH_BODY      <- 94   
CUSTOM_ANI_MAGE_AVATAREND_BODY       <- 95   
CUSTOM_ANI_MAGE_BELLANEWCHANGE       <- 96   
CUSTOM_ANI_MAGE_AVATARREADYB_BODY      <- 97   
CUSTOM_ANI_MAGE_QUASAREXPLOSIONCBODY_BODY    <- 98   
CUSTOM_ANI_MAGE_DRAGONSPEARNEW_BODY      <- 99   
CUSTOM_ANI_MAGE_ELEMENTALCURTAIN_CAST_BODY    <- 111   
CUSTOM_ANI_MAGE_ELEMENTALCURTAIN_SHOOT_BODY    <- 112   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGSTART_BODY   <- 113   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGLOOPA_BODY   <- 114   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGLOOPB_BODY   <- 115   
CUSTOM_ANI_MAGE_ELEMENTALQUAKE_CASTINGEND_BODY   <- 116   
CUSTOM_ANI_MAGE_CRYSTALOFOVERMIND_SUMMON_BODY   <- 117   
CUSTOM_ANI_MAGE_THEGATECAST_BODY       <- 118   
CUSTOM_ANI_MAGE_SESTOELEMENTOCAST      <- 119   
CUSTOM_ANI_MAGE_SESTOELEMENTOCHARGE      <- 120   
CUSTOM_ANI_MAGE_SESTOELEMENTOREADY      <- 121   
CUSTOM_ANI_MAGE_SESTOELEMENTOEXP       <- 122   
CUSTOM_ANI_MAGE_ELECRABBITSTART       <- 123   
CUSTOM_ANI_MAGE_ELECRABBITLOOP       <- 124   
CUSTOM_ANI_MAGE_ELECRABBITLOOPFAIL      <- 125   
CUSTOM_ANI_MAGE_ELECRABBITEND       <- 126   
CUSTOM_ANI_MAGE_ELECRABBITENDFAIL      <- 127   
CUSTOM_ANI_MAGE_LOLLIPOPCRUSH       <- 128   
CUSTOM_ANI_MAGE_LOLLIPOPCRUSHAIRCAST_BODY    <- 129   
CUSTOM_ANI_MAGE_UROBOROSSTART       <- 130   
CUSTOM_ANI_MAGE_UROBOROSREADY       <- 131   
CUSTOM_ANI_MAGE_UROBOROSIDLE        <- 132   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERCAST_BODY    <- 133   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERSTARTBACK_BODY   <- 134   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACK_BODY   <- 135   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACKBOUNCE01A_BODY <- 136   
CUSTOM_ANI_MAGE_JACKFROSTICEWATERLOOPBACKBOUNCE02_BODY <- 137   
CUSTOM_ANI_MAGE_MOONSHADOWLAUNCH_BODY     <- 138   
CUSTOM_ANI_MAGE_REPEATEDSMASHOFRAGECHARGE    <- 139   
CUSTOM_ANI_MAGE_REPEATEDSMASHOFRAGESHOOT     <- 140   
CUSTOM_ANI_MAGE_SUMMONRAMOSCAST       <- 141   
CUSTOM_ANI_MAGE_BUGFALLCASTBODYCAST      <- 142   
CUSTOM_ANI_MAGE_BUGFALLCASTBODYSHOOT      <- 143   


 
 
CUSTOM_ATTACK_MAGE_CHASERCLUSTERPUSH      <- 38    
CUSTOM_ATTACK_MAGE_AVATARDANCERIGHTSLASH     <- 39    
CUSTOM_ATTACK_MAGE_AVATARDANCELEFTSLASH     <- 40    
CUSTOM_ATTACK_MAGE_AVATARDANCEPUSHATTACK     <- 41    
CUSTOM_ATTACK_MAGE_AVATARDANCEJUMPUPPER     <- 42    
CUSTOM_ATTACK_MAGE_AVATARDANCEDUNKSLASH     <- 43    
CUSTOM_ATTACK_MAGE_AVATARCAST       <- 44    
CUSTOM_ATTACK_MAGE_DRAGONDANCEATTACK      <- 45    
CUSTOM_ATTACK_MAGE_DRAGONDANCEATTACKFINISH    <- 46    
CUSTOM_ATTACK_MAGE_RANDOMPIERCESTRIKELOOPBELLATRIX  <- 47    
CUSTOM_ATTACK_MAGE_RANDOMPIERCESTRIKEFINISHBELLATRIX  <- 48    
CUSTOM_ATTACK_MAGE_LOLLIPOPCRUSH       <- 49    
CUSTOM_ATTACK_MAGE_UROBOROSMULTIHIT      <- 50    




 


 
 
PASSIVEOBJ_SUB_STATE_0   <- 10
PASSIVEOBJ_SUB_STATE_1   <- 11
PASSIVEOBJ_SUB_STATE_2   <- 12
PASSIVEOBJ_SUB_STATE_3   <- 13
PASSIVEOBJ_SUB_STATE_4   <- 14
PASSIVEOBJ_SUB_STATE_5   <- 15
PASSIVEOBJ_SUB_STATE_6   <- 16
PASSIVEOBJ_SUB_STATE_7   <- 17
PASSIVEOBJ_SUB_STATE_8   <- 18
PASSIVEOBJ_SUB_STATE_9   <- 19
 


 
 
APID_MAGE_AVATAR_ICON       <- 245    
APID_MAGE_AVATAR         <- 246    
APID_MAGE_SUMMONHEILROM       <- 138    
 


 
 
SOUND_ID_MAGE_AVATAR        <- 9001    
SOUND_ID_MAGE_RAIDP_CHARGE_LOOP     <- 9002    
SOUND_ID_MAGE_WZ_ELEMENTALCURTAIN_01_1   <- 9003    
SOUND_ID_MAGE_WZ_ELEMENTALQUAKE_02_1    <- 9004    
SOUND_ID_MAGE_WZ_CRYSTALOVERMIND_01_1   <- 9005    
SOUND_ID_MAGE_UROBOROS_ROTATE_LOOP    <- 9006    
SOUND_ID_MAGE_JACKFROST_ICEWATER_ROLL_LOOP  <- 9007    

 
 
MONSTER_INDEX_MAGE_SUMMONKRUTA  <- 50680731  
MONSTER_INDEX_MAGE_SUMMONRAMOS  <- 50680732  
MONSTER_INDEX_MAGE_SUMMONHEILROM <- 50680733  

 
MONSTER_ZPOS_MAGE_SUMMONKRUTA  <- 1111  
MONSTER_ZPOS_MAGE_SUMMONRAMOS  <- 1112  
MONSTER_ZPOS_MAGE_SUMMONHEILROM  <- 1113  
 

