
STATE_STAND <- 0
STATE_SIT <- 1
STATE_SIT_FOREVER <- 2
STATE_DAMAGE <- 3
STATE_DOWN <- 4
STATE_DIE <- 5
STATE_JUMP <- 6
STATE_JUMP_ATTACK <- 7
STATE_ATTACK <- 8
STATE_HOLD <- 9
STATE_SUMMONSTART <- 10
STATE_SUMMONEND <- 11
STATE_UNSUMMON <- 12
STATE_THROW <- 13
STATE_DASH <- 14
STATE_DASH_ATTACK <- 15
STATE_GET_ITEM <- 16
STATE_BUFF <- 17
STATE_QUICK_STANDING <- 18
STATE_GE_DANG <- 19
STATE_GEI_ZHAN <- 20
STATE_NI_XIANG_FAN_JI <- 21
STATE_SAN_DUAN_ZHAN <- 22
STATE_BA_DAO_ZHAN <- 23
STATE_DI_LIE_BO_DONG_JIAN <- 24
STATE_YING_GUANG_LUO_REN <- 25
STATE_SHI_HUN_ZHI_SHOU <- 26
STATE_XIE_GUANG_ZHAN <- 27
STATE_WEIZHI1 <- 28
STATE_LIAN_TU_CI <- 29
STATE_WEIZHI2 <- 30
STATE_XIE_GUANG_BO_DONG_ZHENG <- 31
STATE_WEIZHI3 <- 32
STATE_GUI_YIN_SHAN <- 33
STATE_WU_SHUANG_BO <- 34
STATE_SHI_ZI_ZHAN <- 35
STATE_BEN_SHAN_JI <- 36
STATE_PO_JUN <- 37
STATE_GUI_YING_ZHU <- 38
STATE_MEN_LONG_DUAN_KONG_ZHAN <- 39
STATE_WEIZHI4 <- 40
STATE_BU_DONG_MING_WANG_BOOM <- 41
STATE_YUE_GUANG_ZHAN <- 42
STATE_SHI_HUN_FEN_MO_ZHAN <- 43
STATE_MING_YAN_KA_LUO_GONG_JI_ZHUANG_TAI <- 44
STATE_BEN_SAN_LIE_DI_ZHAN <- 45
STATE_YU_XUE_MO_SHA_ZHONG_JIE <- 46
STATE_BAO_FEN_SHI_TAI_SHOU <- 47
STATE_BAO_FEN_SHI_LIAN_XV_ZHAN_JI <- 48
STATE_BAO_FEN_SHI_ZHONG_JIE_GON_JI <- 49
STATE_BU_LA_XIU <- 50
STATE_AN_TIAN_BO_DON_YAN_CAST <- 51
STATE_AN_TIAN_BO_DON_YAN_ICE_WAVE <- 52
STATE_AN_TIAN_BO_DON_YAN_NONE_WAVE <- 53
STATE_AN_TIAN_BO_DON_YAN_FIRE_WAVE <- 54
STATE_MU_BEI_SAN_JUE_ZHEN <- 55
STATE_PO_KONG_BA_DAO_ZHAN <- 56
STATE_XUE_QI_BAO_FA <- 57
STATE_PO_JUN_ZHAN_LONG_JI <- 58
STATE_WEIZHI5 <- 59
STATE_XUE_JIAN <- 60
STATE_LIU <- 61
STATE_LIU_CI <- 62
STATE_LIU_YUE <- 63
STATE_LIU_SHENG <- 64
STATE_GUI_YIN_BIAN <- 65
STATE_GUI_YIN_SAN_JIE_JI <- 66

STATE_SWORDMAN1					<- 100
STATE_SWORDMAN2					<- 101
STATE_SWORDMAN3					<- 102
STATE_SWORDMAN4					<- 103
STATE_SWORDMAN5					<- 104

STATE_SWORDMAN_BLOODBOOM         <- 229    
STATE_SWORDMAN_BLOODMARBLE         <- 230    
STATE_SWORDMAN_BLOODRIVEN         <- 231    
STATE_SWORDMAN_RAGE           <- 232    
STATE_SWORDMAN_BLOODSNATCH         <- 233    
STATE_SWORDMAN_SWORDOFMIND         <- 234    
STATE_SWORDMAN_METEORSWORD         <- 235    
STATE_SWORDMAN_FLASHCUT          <- 236    
STATE_SWORDMAN_SLASHOFBOOM         <- 237    
STATE_SWORDMAN_SLASHOFHELL         <- 238    
STATE_SWORDMAN_BLADEPHANTOM         <- 239    
STATE_SWORDMAN_BLADEPHANTOMEX        <- 240    
STATE_SWORDMAN_ZIGADVENT         <- 241    
STATE_SWORDMAN_INDARAMANG         <- 242    
STATE_SWORDMAN_VAJRA          <- 243    
STATE_SWORDMAN_LIGHTNINGGOD         <- 244    
STATE_SWORDMAN_FATALBLOOD         <- 245    
STATE_SWORDMAN_HANDLINGSWORD        <- 246    
STATE_SWORDMAN_TOMBSTONESWAMP        <- 247    
STATE_NECROMANTIC				    <- 113

SKILL_DEFANEBLOOD <- 251
SKILL_FORCETHUNDERER		<-252
SKILL_GHOSTSOUL_RELEASE <- 26
SKILL_NECROMANTIC				<- 113

SKILL_SWORDMAN_BLOODYVIGOROUS        <- 63    
SKILL_SWORDMAN_BLOODBOOM         <- 229    
SKILL_SWORDMAN_BLOODMARBLE         <- 230    
SKILL_SWORDMAN_BLOODRIVEN         <- 231    
SKILL_SWORDMAN_RAGE           <- 232    
SKILL_SWORDMAN_BLOODSNATCH         <- 233    
SKILL_SWORDMAN_SWORDOFMIND         <- 234    
SKILL_SWORDMAN_METEORSWORD         <- 235    
SKILL_SWORDMAN_FLASHCUT          <- 236    
SKILL_SWORDMAN_SLASHOFBOOM         <- 237    
SKILL_SWORDMAN_SLASHOFHELL         <- 238    
SKILL_SWORDMAN_BLADEPHANTOM         <- 239    
SKILL_SWORDMAN_BLADEPHANTOMEX        <- 240    
SKILL_SWORDMAN_ZIGADVENT         <- 241    
SKILL_SWORDMAN_INDARAMANG         <- 242    
SKILL_SWORDMAN_VAJRA          <- 243    
SKILL_SWORDMAN_LIGHTNINGGOD         <- 244    
SKILL_SWORDMAN_FATALBLOOD         <- 245    
SKILL_SWORDMAN_HANDLINGSWORD        <- 246    
SKILL_SWORDMAN_TOMBSTONESWAMP        <- 247    
SKILL_SWORDMAN_STATEOFLIMIT         <- 248    
SKILL_SWORDMAN_COMMINTERRUPT         <- 254    
SKILL_SWORDMAN_JIQUZHILI				<- 28
SKILL_SWORDMAN_MYSTICEQUIP	<- 249
 
 
CUSTOM_ANI_SWORDMAN_GRAB         <- 10    
CUSTOM_ANI_SWORDMAN_BLOODBOOM        <- 122    
CUSTOM_ANI_SWORDMAN_BLOODRIVENCAST       <- 123    
CUSTOM_ANI_SWORDMAN_BLOODRIVENCHARGE      <- 124    
CUSTOM_ANI_SWORDMAN_BLOODRIVENCHANGE      <- 125    
CUSTOM_ANI_SWORDMAN_BLOODRIVENJUMP       <- 126    
CUSTOM_ANI_SWORDMAN_BLOODRIVENFINISH      <- 127    
CUSTOM_ANI_SWORDMAN_BLOODMARBLEEXTRACTREADY_BODY   <- 128    
CUSTOM_ANI_SWORDMAN_RAGESTARTBODY_BODY      <- 129    
CUSTOM_ANI_SWORDMAN_RAGELOOP01BODY_BODY      <- 130    
CUSTOM_ANI_SWORDMAN_RAGELOOP02BODY_BODY      <- 131    
CUSTOM_ANI_SWORDMAN_RAGELOOP03BODY_BODY      <- 132    
CUSTOM_ANI_SWORDMAN_RAGELOOP04BODY_BODY      <- 133    
CUSTOM_ANI_SWORDMAN_RAGEENDBODY_BODY      <- 134    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCAST_BODY     <- 135    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASH_BODY     <- 136    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCATCH_BODY     <- 137    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASHCATCH_BODY    <- 138    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHSPIN_BODY     <- 139    
CUSTOM_ANI_SWORDMAN_BLOODSNATCHFINISH_BODY     <- 140    
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGE      <- 141    
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGEATTRACT    <- 142    
CUSTOM_ANI_SWORDMAN_SWORDOFMINDCHARGEATTACK     <- 143    
CUSTOM_ANI_SWORDMAN_METEORSWORDSTART      <- 144    
CUSTOM_ANI_SWORDMAN_METEORSWORDCHARGE      <- 145    
CUSTOM_ANI_SWORDMAN_METEORSWORDCHARGEFINISH     <- 146    
CUSTOM_ANI_SWORDMAN_METEORSWORDUP       <- 147    
CUSTOM_ANI_SWORDMAN_METEORSWORDDROP       <- 148    
CUSTOM_ANI_SWORDMAN_METEORSWORDEXPLOSION     <- 149    
CUSTOM_ANI_SWORDMAN_FLASHCUTREADY_BODY      <- 150    
CUSTOM_ANI_SWORDMAN_FLASHCUTATK_BODY      <- 151    
CUSTOM_ANI_SWORDMAN_FLASHCUTEND_BODY      <- 152    
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_READY      <- 153    
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_ATTACK      <- 154    
CUSTOM_ANI_SWORDMAN_SLASHOFHELL        <- 155    
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_CAST_BODY    <- 156    
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_JUMP_BODY    <- 157    
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_SLASH_BODY    <- 158    
CUSTOM_ANI_SWORDMAN_ZIGADVENT_NEW       <- 159    
CUSTOM_ANI_SWORDMAN_INDARAMANG        <- 160    
CUSTOM_ANI_SWORDMAN_VAJRACAST        <- 161    
CUSTOM_ANI_SWORDMAN_VAJRAFINISH        <- 162    
CUSTOM_ANI_SWORDMAN_LIGHTNINGGOD       <- 163    
CUSTOM_ANI_SWORDMAN_FATALBLOOD1HIT_BODY      <- 164    
CUSTOM_ANI_SWORDMAN_FATALBLOOD2HIT_BODY      <- 165    
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HIT_BODY      <- 166    
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HITFAIL_BODY     <- 167    
CUSTOM_ANI_SWORDMAN_HANDLINGSWORD_SRART_BODY    <- 168    
CUSTOM_ANI_SWORDMAN_TOMBSTONESWAMP_BODY      <- 169    


 
 
CUSTOM_ATTACK_SWORDMAN_BLOODRIVENMULTIHIT     <- 87    
CUSTOM_ATTACK_SWORDMAN_BLOODRIVENCHARGEHIT     <- 88    
CUSTOM_ATTACK_SWORDMAN_RAGE_ATK3       <- 89    
CUSTOM_ATTACK_SWORDMAN_BLOODSNATCH       <- 90    
CUSTOM_ATTACK_SWORDMAN_SWORDOFMINDATTACK     <- 91    
CUSTOM_ATTACK_SWORDMAN_METEORSWORDEXPLOSION     <- 92    
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACK     <- 93    
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACKFINISH   <- 94    
CUSTOM_ATTACK_SWORDMAN_SLASHOFHELL       <- 95    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD1HIT      <- 96    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD2HIT      <- 97    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD3HIT      <- 98    
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD4HIT      <- 99    

 


 
 
PASSIVEOBJ_SUB_STATE_0        <- 10
PASSIVEOBJ_SUB_STATE_1        <- 11
PASSIVEOBJ_SUB_STATE_2        <- 12
PASSIVEOBJ_SUB_STATE_3        <- 13
PASSIVEOBJ_SUB_STATE_4        <- 14
PASSIVEOBJ_SUB_STATE_5        <- 15
PASSIVEOBJ_SUB_STATE_6        <- 16
PASSIVEOBJ_SUB_STATE_7        <- 17
 


 
 
APID_SWORDMAN_HANDLINGSWORD         <- 229   

CUSTOM_ANI_GRAB         <- 10
CUSTOM_ANI_BLOODBOOM        <- 122
CUSTOM_ANI_BLOODRIVENCAST       <- 123
CUSTOM_ANI_BLOODRIVENCHARGE      <- 124
CUSTOM_ANI_BLOODRIVENCHANGE      <- 125
CUSTOM_ANI_BLOODRIVENJUMP       <- 126
CUSTOM_ANI_BLOODRIVENFINISH      <- 127
CUSTOM_ANI_BLOODMARBLEEXTRACTREADY_BODY   <- 128
CUSTOM_ANI_SWORDMAN_RAGESTARTBODY_BODY      		<- 129
CUSTOM_ANI_SWORDMAN_RAGELOOP01BODY_BODY      		<- 130
CUSTOM_ANI_SWORDMAN_RAGELOOP02BODY_BODY      		<- 131
CUSTOM_ANI_SWORDMAN_RAGELOOP03BODY_BODY      		<- 132
CUSTOM_ANI_SWORDMAN_RAGELOOP04BODY_BODY      		<- 133
CUSTOM_ANI_SWORDMAN_RAGEENDBODY_BODY      			<- 134
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCAST_BODY     		<- 135
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASH_BODY     		<- 136
CUSTOM_ANI_SWORDMAN_BLOODSNATCHCATCH_BODY     		<- 137
CUSTOM_ANI_SWORDMAN_BLOODSNATCHDASHCATCH_BODY    	<- 138
CUSTOM_ANI_SWORDMAN_BLOODSNATCHSPIN_BODY     		<- 139
CUSTOM_ANI_SWORDMAN_BLOODSNATCHFINISH_BODY     		<- 140
CUSTOM_ANI_SWORDOFMINDCHARGE      <- 141
CUSTOM_ANI_SWORDOFMINDCHARGEATTRACT    <- 142
CUSTOM_ANI_SWORDOFMINDCHARGEATTACK     <- 143
CUSTOM_ANI_METEORSWORDSTART      <- 144
CUSTOM_ANI_METEORSWORDCHARGE      <- 145
CUSTOM_ANI_METEORSWORDCHARGEFINISH     <- 146
CUSTOM_ANI_METEORSWORDUP       <- 147
CUSTOM_ANI_METEORSWORDDROP       <- 148
CUSTOM_ANI_METEORSWORDEXPLOSION     <- 149
CUSTOM_ANI_SWORDMAN_FLASHCUTREADY_BODY      <- 150
CUSTOM_ANI_SWORDMAN_FLASHCUTATK_BODY      <- 151
CUSTOM_ANI_SWORDMAN_FLASHCUTEND_BODY      <- 152
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_READY      			<- 153
CUSTOM_ANI_SWORDMAN_SLASHOFBOOM_ATTACK      		<- 154
CUSTOM_ANI_SWORDMAN_SLASHOFHELL        <- 155
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_CAST_BODY    <- 156
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_JUMP_BODY    <- 157
CUSTOM_ANI_SWORDMAN_BLADEPHANTOMEX_SLASH_BODY    <- 158
CUSTOM_ANI_ZIGADVENT_NEW       <- 159
CUSTOM_ANI_INDARAMANG        <- 160
CUSTOM_ANI_VAJRACAST        <- 161
CUSTOM_ANI_VAJRAFINISH        <- 162
CUSTOM_ANI_LIGHTNINGGOD       <- 163
CUSTOM_ANI_SWORDMAN_FATALBLOOD1HIT_BODY      		<- 164
CUSTOM_ANI_SWORDMAN_FATALBLOOD2HIT_BODY      		<- 165
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HIT_BODY      		<- 166
CUSTOM_ANI_SWORDMAN_FATALBLOOD3HITFAIL_BODY     	<- 167
CUSTOM_ANI_SWORDMAN_TOMBSTONESWAMP_BODY      		<- 169
CUSTOM_ANI_HANDLINGSWORD_SRART_BODY    <- 168
CUSTOM_ANI_THROW1							<- 171
CUSTOM_ANI_THROW2							<- 172

CUSTOM_ANI_YIN_READY		<-	174
CUSTOM_ANI_YIN_ATTACK_0		<-	175
CUSTOM_ANI_YIN_ATTACK_1		<-	176
CUSTOM_ANI_YIN_ATTACK_2		<-	177
CUSTOM_ANI_ATTACK1		<-	178
CUSTOM_ANI_ATTACK2		<-	179
CUSTOM_ANI_ATTACK3		<-	180
CUSTOM_ANI_SANGUANGCHONGFENG_R		<-	181
CUSTOM_ANI_SANGUANGCHONGFENG_A1		<-	182
CUSTOM_ANI_SANGUANGCHONGFENG_END		<-	183
CUSTOM_ANI_NULL		<-	184
CUSTOM_ANI_NULL		<-	185
CUSTOM_ANI_WANXIANGJIANZHEN		<-	186
CUSTOM_ANI_XUESETULI_START		<-	187
CUSTOM_ANI_XUESETULI_ATK1		<-	188
CUSTOM_ANI_XUESETULI_ATK2		<-	189
CUSTOM_ANI_XUESETULI_ATK3		<-	190
CUSTOM_ANI_XUESETULI_END		<-	191
CUSTOM_ANI_UP_ATTACK		<-	192
CUSTOM_ANI_BACK_JUMP		<-	193
CUSTOM_ANI_GHOST_CHANGE_CAST		<-	194
CUSTOM_ANI_GHOST_CHANGE_END		<-	195
CUSTOM_ANI_GHOST_CHANGE_DARK_ATTACK1		<-	196
CUSTOM_ANI_GHOST_CHANGE_DARK_ATTACK2		<-	197
CUSTOM_ANI_GHOST_CHANGE_RAD_ATTACK1		<-	198
CUSTOM_ANI_GHOST_CHANGE_RAD_ATTACK2		<-	199

CUSTOM_ATTACK_BLOODRIVENMULTIHIT     <- 87
CUSTOM_ATTACK_BLOODRIVENCHARGEHIT     <- 88
CUSTOM_ATTACK_SWORDMAN_RAGE_ATK3       <- 89
CUSTOM_ATTACK_SWORDMAN_BLOODSNATCH       <- 90
CUSTOM_ATTACK_SWORDOFMINDATTACK     <- 91
CUSTOM_ATTACK_METEORSWORDEXPLOSION     <- 92
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACK     <- 93
CUSTOM_ATTACK_SWORDMAN_FLASHCUTDELAYATTACKFINISH   <- 94
CUSTOM_ATTACK_SWORDMAN_SLASHOFHELL       <- 95
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD1HIT      <- 96
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD2HIT      <- 97
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD3HIT      <- 98
CUSTOM_ATTACK_SWORDMAN_FATALBLOOD4HIT      <- 99


//GuiQi_optimize-----------start-----
Skill_KaZan_25					<- 25
Skill_PuLiMeng_41				<- 41
Skill_SaYa_36					<- 36
Skill_MuBei_44					<- 44
Skill_YuGuangZhan_77			<- 77
Skill_GuiYinShan_60				<- 60
Skill_LieBoZhan_58				<- 58
Skill_GuiYinBian_111			<- 111
Skill_GuiYinSanJian_112			<- 112
Skill_AnYue_30					<- 30
Skill_GuiZhan_05				<- 05
Skill_LuoCha_75					<- 75
Skill_GuiYinShanEX_226			<- 226
Skill_KaLuo_82			<- 82

State_YuGuangZhan_42			<- 42
State_GuiYinShan_33				<- 33
State_LieBoZhan_32				<- 32
State_GuiYinBian_65				<- 65
State_GuiYinSanJian_66			<- 66
State_MuBeiNew_74				<- 74
State_AnYueNew_75				<- 75
State_GuiZhan_20				<- 20
State_KaLuo_44				<- 44

APID_Dark					<- 256

ANI_SpiritAttack1				<- 115
ANI_SpiritAttack2				<- 116
ANI_SpiritAttack3				<- 117
ANI_SpiritAttack4				<- 118

//GuiQi_optimize-----------end-----