
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


 
 
 
STATE_ATFIGHTER_SPIRALEMPERORSLAP       <- 220    
STATE_ATFIGHTER_MOONLIGHTTHEEARTH       <- 221    
STATE_ATFIGHTER_GLANCETHEHOST        <- 222    
STATE_ATFIGHTER_DROPFIRE         <- 223    
STATE_ATFIGHTER_ATOMICCANNON        <- 224    
STATE_ATFIGHTER_EMPERORCOMBINATION       <- 225    
STATE_ATFIGHTER_CHAINDRIVE         <- 226    
STATE_ATFIGHTER_RUINRAIN         <- 227    
STATE_ATFIGHTER_FIREWORKS         <- 228    
STATE_ATFIGHTER_CYCLONECRASH        <- 229    
STATE_ATFIGHTER_CHAINBRAKE         <- 230    
STATE_ATFIGHTER_FINALEXTREMESTRIKE       <- 231    



 
 
SKILL_ATFIGHTER_SPIRALEMPERORSLAP       <- 220    
SKILL_ATFIGHTER_MOONLIGHTTHEEARTH       <- 221    
SKILL_ATFIGHTER_GLANCETHEHOST        <- 222    
SKILL_ATFIGHTER_DROPFIRE         <- 223    
SKILL_ATFIGHTER_ATOMICCANNON        <- 224    
SKILL_ATFIGHTER_EMPERORCOMBINATION       <- 225    
SKILL_ATFIGHTER_CHAINDRIVE         <- 226    
SKILL_ATFIGHTER_RUINRAIN         <- 227    
SKILL_ATFIGHTER_FIREWORKS         <- 228    
SKILL_ATFIGHTER_CYCLONECRASH        <- 229    
SKILL_ATFIGHTER_CHAINBRAKE         <- 230    
SKILL_ATFIGHTER_FINALEXTREMESTRIKE       <- 231    



 
 
CUSTOM_ANI_ATFIGHTER_MOONLIGHTTHEEARTH_BODY_START   <- 142    
CUSTOM_ANI_ATFIGHTER_MOONLIGHTTHEEARTH_BODY_LOOP   <- 143    
CUSTOM_ANI_ATFIGHTER_MOONLIGHTTHEEARTH_BODY_END    <- 144    
CUSTOM_ANI_ATFIGHTER_SPIRALEMPERORSLAP_START_BODY   <- 145    
CUSTOM_ANI_ATFIGHTER_SPIRALEMPERORSLAP_START_FAIL_BODY  <- 146    
CUSTOM_ANI_ATFIGHTER_SPIRALEMPERORSLAP_START_SUCCESS_BODY <- 147    
CUSTOM_ANI_ATFIGHTER_SPIRALEMPERORSLAP_LOOP_BODY   <- 148    
CUSTOM_ANI_ATFIGHTER_SPIRALEMPERORSLAP_END_BODY    <- 149    
CUSTOM_ANI_ATFIGHTER_GLANCETHEHOST_CAST      <- 150    
CUSTOM_ANI_ATFIGHTER_GLANCETHEHOST_START     <- 151    
CUSTOM_ANI_ATFIGHTER_GLANCETHEHOST_GATHERING    <- 152    
CUSTOM_ANI_ATFIGHTER_GLANCETHEHOST_END      <- 153    
CUSTOM_ANI_ATFIGHTER_ATDROPFIRE_BODY_JUMP     <- 154    
CUSTOM_ANI_ATFIGHTER_ATDROPFIRE_BODY      <- 155    
CUSTOM_ANI_ATFIGHTER_ATOMICCANNON_BODY_READY    <- 156    
CUSTOM_ANI_ATFIGHTER_ATOMICCANNON_BODY_CHARGE    <- 157    
CUSTOM_ANI_ATFIGHTER_ATOMICCANNON_BODY_CHARGE_END   <- 158    
CUSTOM_ANI_ATFIGHTER_ATOMICCANNON_BODY_RUSH     <- 159    
CUSTOM_ANI_ATFIGHTER_ATOMICCANNON_BODY_PUNCH    <- 160    
CUSTOM_ANI_ATFIGHTER_EMPERORCOMBINATIONBODY_01    <- 161    
CUSTOM_ANI_ATFIGHTER_EMPERORCOMBINATIONBODY_02    <- 162    
CUSTOM_ANI_ATFIGHTER_EMPERORCOMBINATIONBODY_03    <- 163    
CUSTOM_ANI_ATFIGHTER_CHAINDRIVESTEP1A_BODY     <- 164    
CUSTOM_ANI_ATFIGHTER_CHAINDRIVESTEP2_BODY     <- 165    
CUSTOM_ANI_ATFIGHTER_CHAINDRIVESTEP3_BODY     <- 166    
CUSTOM_ANI_ATFIGHTER_CHAINDRIVESTEP4_BODY     <- 167    
CUSTOM_ANI_ATFIGHTER_RUINRAIN_BODY       <- 168    
CUSTOM_ANI_ATFIGHTER_FIREWORKS_CAST_BODY     <- 169    
CUSTOM_ANI_ATFIGHTER_FIREWORKS_START_BODY     <- 170    
CUSTOM_ANI_ATFIGHTER_FIREWORKS_HIT_BODY      <- 171    
CUSTOM_ANI_ATFIGHTER_FIREWORKS_END_BODY      <- 172    
CUSTOM_ANI_ATFIGHTER_CYCLONECRASHTRYDEFINITEGRABBODY  <- 173    
CUSTOM_ANI_ATFIGHTER_CYCLONECRASHTRYGRABBODY    <- 174    
CUSTOM_ANI_ATFIGHTER_CYCLONECRASHTHROWBODY     <- 175    
CUSTOM_ANI_ATFIGHTER_CYCLONECRASHGRABCANNONBODY    <- 176    
CUSTOM_ANI_ATFIGHTER_NNCB_READY        <- 177    
CUSTOM_ANI_ATFIGHTER_NNDASHBODYEE       <- 178    
CUSTOM_ANI_ATFIGHTER_NNDASHBODY        <- 179    
CUSTOM_ANI_ATFIGHTER_NNFINISH_READY_BODYA     <- 180    
CUSTOM_ANI_ATFIGHTER_NNFINISH_READY_BODYB     <- 181    
CUSTOM_ANI_ATFIGHTER_NNFINISH_READY_BODYC     <- 182    
CUSTOM_ANI_ATFIGHTER_NNFINISH_ATKBODY      <- 183    
CUSTOM_ANI_ATFIGHTER_FINISHNOGRAPBODY_11     <- 184    
CUSTOM_ANI_ATFIGHTER_ASTART1_BODY       <- 185    
CUSTOM_ANI_ATFIGHTER_ASTART2_BODY       <- 186    
CUSTOM_ANI_ATFIGHTER_BSTART1_BODY       <- 187    
CUSTOM_ANI_ATFIGHTER_BSTART2_BODY       <- 188    
CUSTOM_ANI_ATFIGHTER_BSTART3_BODY       <- 189    
CUSTOM_ANI_ATFIGHTER_C1_BODY        <- 190    
CUSTOM_ANI_ATFIGHTER_C2_BODY        <- 191    
CUSTOM_ANI_ATFIGHTER_B16_BODY        <- 192    
CUSTOM_ANI_ATFIGHTER_D_BODY         <- 193    
CUSTOM_ANI_ATFIGHTER_DGRAB_BODY        <- 194    
CUSTOM_ANI_ATFIGHTER_DNOTGRAB_BODY       <- 195    
CUSTOM_ANI_ATFIGHTER_EBODY1_BODY       <- 196    
CUSTOM_ANI_ATFIGHTER_EBODY2_BODY       <- 197    
CUSTOM_ANI_ATFIREPOWERRELEASE_BODY       <- 198    


 
 
CUSTOM_ATTACK_ATFIGHTER_MOONLIGHTTHEEARTH     <- 86    
CUSTOM_ATTACK_ATFIGHTER_SPIRALEMPERORSLAPATTACKTRY   <- 87    
CUSTOM_ATTACK_ATFIGHTER_GLANCETHEHOSTGATHERING    <- 88    
CUSTOM_ATTACK_ATFIGHTER_GLANCETHEHOSTEXP     <- 89    
CUSTOM_ATTACK_ATFIGHTER_DROPFIREKICK      <- 90    
CUSTOM_ATTACK_ATFIGHTER_ATOMICCANNONRUSH     <- 91    
CUSTOM_ATTACK_ATFIGHTER_ATOMICCANNONPUNCH     <- 92    
CUSTOM_ATTACK_ATFIGHTER_EMPERORCOMBINATIONATTACK1   <- 93    
CUSTOM_ATTACK_ATFIGHTER_EMPERORCOMBINATIONATTACK2   <- 94    
CUSTOM_ATTACK_ATFIGHTER_EMPERORCOMBINATIONATTACK3   <- 95    
CUSTOM_ATTACK_ATFIGHTER_EMPERORCOMBINATIONSTUNATTACK  <- 96    
CUSTOM_ATTACK_ATFIGHTER_CHAINDRIVESWING      <- 97    
CUSTOM_ATTACK_ATFIGHTER_FIREWORKSTAUNT      <- 98    
CUSTOM_ATTACK_ATFIGHTER_FIREWORKSIRONPIPE     <- 99    
CUSTOM_ATTACK_ATFIGHTER_CYCLONECRASHTRYGRAB     <- 100    
CUSTOM_ATTACK_ATFIGHTER_CHAINBRAKEGRAB      <- 101    
CUSTOM_ATTACK_ATFIGHTER_CHAINBRAKEGRABFINISH    <- 102    
CUSTOM_ATTACK_ATFIGHTER_FINALEXTREMESTRIKESTART    <- 103    
CUSTOM_ATTACK_ATFIGHTER_FINALEXTREMESTRIKEAROUNNDGRAB  <- 104    


 


 
 
PASSIVEOBJ_SUB_STATE_0 <- 10
PASSIVEOBJ_SUB_STATE_1 <- 11
PASSIVEOBJ_SUB_STATE_2 <- 12
PASSIVEOBJ_SUB_STATE_3 <- 13
PASSIVEOBJ_SUB_STATE_4 <- 14
PASSIVEOBJ_SUB_STATE_5 <- 15
PASSIVEOBJ_SUB_STATE_6 <- 16
PASSIVEOBJ_SUB_STATE_7 <- 17
PASSIVEOBJ_SUB_STATE_8 <- 18
PASSIVEOBJ_SUB_STATE_9 <- 19
 


 
 
 

 


 
 
SOUND_ID_ATFIGHTER_SPIRAL_EMPEROSLAP_LOOP     <- 9701    

 