
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


 
 
 
STATE_FIGHTER_LIGHTDRAGONTHIRTEEN      <- 225    
STATE_FIGHTER_SAINTILLUSION        <- 226    
STATE_FIGHTER_ABSORBENERGYBALL       <- 227    
STATE_FIGHTER_NENOFBRILLIANCE       <- 228    
STATE_FIGHTER_ONEELBOWCHAINHIT       <- 229    
STATE_FIGHTER_TIGERSTRIKE        <- 230    
STATE_FIGHTER_CHAINDESTRUCTION       <- 231    
STATE_FIGHTER_FINALHEAVEN        <- 232    
STATE_FIGHTER_POISONEXPLOSION       <- 233    
STATE_FIGHTER_DRAGONMINE        <- 234    
STATE_FIGHTER_POISONSNAKE        <- 235    
STATE_FIGHTER_SNAKECAVE         <- 236    
STATE_FIGHTER_ELBOWTHROW        <- 237    
STATE_FIGHTER_TORBELLINO        <- 238    
STATE_FIGHTER_HURRICANESUPERSUPLEX      <- 239    
STATE_FIGHTER_TURNHEEL         <- 240    



 
 
SKILL_FIGHTER_LIGHTDRAGONTHIRTEEN      <- 225    
SKILL_FIGHTER_SAINTILLUSION        <- 226    
SKILL_FIGHTER_ABSORBENERGYBALL       <- 227    
SKILL_FIGHTER_NENOFBRILLIANCE       <- 228    
SKILL_FIGHTER_ONEELBOWCHAINHIT       <- 229    
SKILL_FIGHTER_TIGERSTRIKE        <- 230    
SKILL_FIGHTER_CHAINDESTRUCTION       <- 231    
SKILL_FIGHTER_FINALHEAVEN        <- 232    
SKILL_FIGHTER_POISONEXPLOSION       <- 233    
SKILL_FIGHTER_DRAGONMINE        <- 234    
SKILL_FIGHTER_POISONSNAKE        <- 235    
SKILL_FIGHTER_SNAKECAVE         <- 236    
SKILL_FIGHTER_ELBOWTHROW        <- 237    
SKILL_FIGHTER_TORBELLINO        <- 238    
SKILL_FIGHTER_HURRICANESUPERSUPLEX      <- 239    
SKILL_FIGHTER_TURNHEEL         <- 240    
SKILL_FIGHTER_COMMINTERRUPT <- 254


 
 
CUSTOM_ANI_FIGHTER_LIGHTDRAGONTHIRTEENSTART_BODY  <- 96    
CUSTOM_ANI_FIGHTER_LIGHTDRAGONTHIRTEENSTARTJUMP_BODY <- 97    
CUSTOM_ANI_FIGHTER_LIGHTDRAGONTHIRTEENNENHIT_BODY  <- 98    
CUSTOM_ANI_FIGHTER_LIGHTDRAGONTHIRTEENLAST_BODY   <- 99    
CUSTOM_ANI_FIGHTER_LIGHTDRAGONTHIRTEENEXPLOSION_BODY <- 100    
CUSTOM_ANI_FIGHTER_SAINTILLUSION_START     <- 101    
CUSTOM_ANI_FIGHTER_SAINTILLUSION_SHOOT1     <- 102    
CUSTOM_ANI_FIGHTER_SAINTILLUSION_SHOOT2     <- 103    
CUSTOM_ANI_FIGHTER_SAINTILLUSION_SHOOT3     <- 104    
CUSTOM_ANI_FIGHTER_SAINTILLUSION_SHOOT_STOP    <- 105    
CUSTOM_ANI_FIGHTER_LV1_START_INHALEDENERGYSHOT_BODY  <- 106    
CUSTOM_ANI_FIGHTER_LV1_LOOP_INHALEDENERGYSHOT_BODY  <- 107    
CUSTOM_ANI_FIGHTER_LV1_SHOOT_INHALEDENERGYSHOT_BODY  <- 108    
CUSTOM_ANI_FIGHTER_NENOFBRILLIANCECAST     <- 109    
CUSTOM_ANI_FIGHTER_NENOFBRILLIANCECHARGE    <- 110    
CUSTOM_ANI_FIGHTER_NENOFBRILLIANCEFINISH    <- 111    
CUSTOM_ANI_FIGHTER_ONEELBOWCHAINHIT_A_BODY    <- 112    
CUSTOM_ANI_FIGHTER_ONEELBOWCHAINHIT_B_BODY    <- 113    
CUSTOM_ANI_FIGHTER_TIGER_START_BODY      <- 114    
CUSTOM_ANI_FIGHTER_TIGER_REPEAT_BODY     <- 115    
CUSTOM_ANI_FIGHTER_TIGER_ENDATK_C_END_BODY    <- 116    
CUSTOM_ANI_FIGHTER_CHAINDESTRUCTION01_NEW    <- 117    
CUSTOM_ANI_FIGHTER_CHAINDESTRUCTION02_NEW    <- 118    
CUSTOM_ANI_FIGHTER_CHAINDESTRUCTION03_NEW    <- 119    
CUSTOM_ANI_FIGHTER_FINALHEAVENSTARTNEW_BODY    <- 120    
CUSTOM_ANI_FIGHTER_FINALHEAVENREADYNEW_BODY    <- 121    
CUSTOM_ANI_FIGHTER_FINALHEAVENATTACKNEW_BODY   <- 122    
CUSTOM_ANI_FIGHTER_POISONEXPLOSION_START_BODY   <- 123    
CUSTOM_ANI_FIGHTER_POISONEXPLOSION_KICK_BODY   <- 124    
CUSTOM_ANI_FIGHTER_DRAGONMINESTART      <- 125    
CUSTOM_ANI_FIGHTER_DRAGONMINEJUMPSPIN     <- 126    
CUSTOM_ANI_FIGHTER_DRAGONMINEIMPACT      <- 127    
CUSTOM_ANI_FIGHTER_DRAGONMINEBOOM      <- 128    
CUSTOM_ANI_FIGHTER_DRAGONMINEDROP      <- 129    
CUSTOM_ANI_FIGHTER_POISONSNAKEATTACK01_BODY    <- 130    
CUSTOM_ANI_FIGHTER_POISONSNAKEATTACK02_BODY    <- 131    
CUSTOM_ANI_FIGHTER_POISONSNAKEATTACK03_BODY    <- 132    
CUSTOM_ANI_FIGHTER_POISONSNAKEATTACK04_BODY    <- 133    
CUSTOM_ANI_FIGHTER_POISONSNAKEATTACK05_BODY    <- 134    
CUSTOM_ANI_FIGHTER_POISONSNAKEDASH_BODY     <- 135    
CUSTOM_ANI_FIGHTER_POISONSNAKEJUMP_BODY     <- 136    
CUSTOM_ANI_FIGHTER_POISONSNAKESTART_BODY    <- 137    
CUSTOM_ANI_FIGHTER_SNAKECAVEREADY1_BODY     <- 138    
CUSTOM_ANI_FIGHTER_SNAKECAVEREADY2_BODY     <- 139    
CUSTOM_ANI_FIGHTER_SNAKECAVEREADYAIR2_BODY    <- 140    
CUSTOM_ANI_FIGHTER_SNAKECAVEREADYAIR3_BODY    <- 141    
CUSTOM_ANI_FIGHTER_SNAKECAVEEXPLOSION_BODY    <- 142    
CUSTOM_ANI_FIGHTER_ELBOWTHROWSTART      <- 143    
CUSTOM_ANI_FIGHTER_ELBOWTHROWEND      <- 144    
CUSTOM_ANI_FIGHTER_ELBOWTHROWLOOP      <- 145    
CUSTOM_ANI_FIGHTER_ELBOWTHROWTURNHEELSTART    <- 146    
CUSTOM_ANI_FIGHTER_ELBOWTHROWTURNHEELLOOP    <- 147    
CUSTOM_ANI_FIGHTER_ELBOWTHROWTURNHEELEND    <- 148    
CUSTOM_ANI_FIGHTER_ELBOWTHROWGC       <- 149    
CUSTOM_ANI_FIGHTER_TORBELLINO_DASH      <- 150    
CUSTOM_ANI_FIGHTER_TORBELLINO_DASHEND_BODY    <- 151    
CUSTOM_ANI_FIGHTER_TORBELLINO_JUMP_BODY     <- 152    
CUSTOM_ANI_FIGHTER_TORBELLINO_END_BODY     <- 153    
CUSTOM_ANI_FIGHTER_TORBELLINO_SPIN      <- 154    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXGRAB    <- 155    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXUPPER   <- 156    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXJUMP    <- 157    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXFALL    <- 158    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXAIRGRAB   <- 159    
CUSTOM_ANI_FIGHTER_HURRICANESUPERSUPLEXFINISH   <- 160    


 
 
CUSTOM_ATTACK_FIGHTER_SAINTILLUSION      <- 58    
CUSTOM_ATTACK_FIGHTER_ONEELBOWCHAINHIT_ONE    <- 59    
CUSTOM_ATTACK_FIGHTER_ONEELBOWCHAINHIT_TWO    <- 60    
CUSTOM_ATTACK_FIGHTER_ONEELBOWCHAINHIT_THREE   <- 61    
CUSTOM_ATTACK_FIGHTER_ONEELBOWCHAINHIT_FINISH   <- 62    
CUSTOM_ATTACK_FIGHTER_TIGERSTRIKEDASH     <- 63    
CUSTOM_ATTACK_FIGHTER_TIGERSTRIKEUPPER     <- 64    
CUSTOM_ATTACK_FIGHTER_CHAINDESTRUCTIONNEW_1    <- 65    
CUSTOM_ATTACK_FIGHTER_CHAINDESTRUCTIONNEW_2    <- 66    
CUSTOM_ATTACK_FIGHTER_CHAINDESTRUCTIONNEW_3    <- 67    
CUSTOM_ATTACK_FIGHTER_CHAINDESTRUCTIONNEW_FINISH  <- 68    
CUSTOM_ATTACK_FIGHTER_FINALHEAVENTRYNEW     <- 69    
CUSTOM_ATTACK_FIGHTER_POISONEXPLOSIONDASH    <- 70    
CUSTOM_ATTACK_FIGHTER_DRAGONMINEDROP     <- 71    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECOMBO1     <- 72    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECOMBO2     <- 73    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECOMBO3     <- 74    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECOMBO4     <- 75    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECASTINGATTACK2   <- 76    
CUSTOM_ATTACK_FIGHTER_POISONSNAKEDASHATTACK    <- 77    
CUSTOM_ATTACK_FIGHTER_POISONSNAKEJUMPATTACK    <- 78    
CUSTOM_ATTACK_FIGHTER_POISONSNAKECASTINGATTACK1   <- 79    
CUSTOM_ATTACK_FIGHTER_SNAKECAVE       <- 80    
CUSTOM_ATTACK_FIGHTER_ELBOWTHROWLOOP     <- 81    
CUSTOM_ATTACK_FIGHTER_ELBOWTHROWGRAB     <- 82    
CUSTOM_ATTACK_FIGHTER_ELBOWTHROWTURNHEELSTART   <- 83    
CUSTOM_ATTACK_FIGHTER_ELBOWTHROWTURNHEELLOOP   <- 84    
CUSTOM_ATTACK_FIGHTER_ELBOWTHROWTURNHEELEND    <- 85    
CUSTOM_ATTACK_FIGHTER_TORBELLINO      <- 86    
CUSTOM_ATTACK_FIGHTER_HURRICANESUPERSUPLEXTURNHEEL  <- 87    
CUSTOM_ATTACK_FIGHTER_HURRICANESUPERSUPLEXUPPER   <- 88    



 


 
 
PASSIVEOBJ_SUB_STATE_0 <- 10
PASSIVEOBJ_SUB_STATE_1 <- 11
PASSIVEOBJ_SUB_STATE_2 <- 12
PASSIVEOBJ_SUB_STATE_3 <- 13
PASSIVEOBJ_SUB_STATE_4 <- 14
PASSIVEOBJ_SUB_STATE_5 <- 15
PASSIVEOBJ_SUB_STATE_6 <- 16
PASSIVEOBJ_SUB_STATE_7 <- 17
PASSIVEOBJ_SUB_STATE_8 <- 18
PASSIVEOBJ_SUB_STATE_9 <- 19
 


 
 
APID_FIGHTER_POISONSNAKE        <- 235    

 


 
 
 

 