
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


SKILL_ICESWORD_UP <- 252
 
 
STATE_ATMAGE_ELEMENTALFIELD        <- 243    
STATE_ATMAGE_CONVERGENCECANNON       <- 244    
STATE_ATMAGE_ARMAGEDDONSTRIKE       <- 245    
STATE_ATMAGE_SHARDMAGNUM        <- 246    
STATE_ATMAGE_OVERFREEZEEXTENSION      <- 247    
STATE_ATMAGE_JUDEKATHEETERNAL       <- 248    



 
 
SKILL_ATMAGE_ELEMENTALFIELD        <- 243    
SKILL_ATMAGE_CONVERGENCECANNON       <- 244    
SKILL_ATMAGE_ARMAGEDDONSTRIKE       <- 245    
SKILL_ATMAGE_SHARDMAGNUM        <- 246    
SKILL_ATMAGE_OVERFREEZEEXTENSION      <- 247    
SKILL_ATMAGE_JUDEKATHEETERNAL       <- 248    


 
 
CUSTOM_ANI_ATMAGE_ELEMENTALFIELD      <- 97    
CUSTOM_ANI_ATMAGE_CONVERGENCECANNONSTART_BODY   <- 98    
CUSTOM_ANI_ATMAGE_CONVERGENCECANNONCREATE_BODY   <- 99    
CUSTOM_ANI_ATMAGE_CONVERGENCECANNONSHOT_BODY   <- 100    
CUSTOM_ANI_ATMAGE_ARMAGEDDONSTRIKESTART_BODY   <- 101    
CUSTOM_ANI_ATMAGE_ARMAGEDDONSTRIKECREATE_BODY   <- 102    
CUSTOM_ANI_ATMAGE_ARMAGEDDONSTRIKEEXPLOSION_BODY  <- 103    
CUSTOM_ANI_ATMAGE_SHARDMAGNUMBODY_BODY     <- 104    
CUSTOM_ANI_ATMAGE_OVERFREEZEEXTENSIONCASTING   <- 105    
CUSTOM_ANI_ATMAGE_OVERFREEZEEXTENSIONATTACK    <- 106    
CUSTOM_ANI_ATMAGE_JUDEKATHEETERNAL_CAST_BODY   <- 107    
CUSTOM_ANI_ATMAGE_JUDEKATHEETERNAL_START_BODY   <- 108    


 
 
CUSTOM_ATTACK_ATMAGE_SHARDMAGNUM      <- 22    



 


 
 
PASSIVEOBJ_SUB_STATE_0         <- 10
PASSIVEOBJ_SUB_STATE_1         <- 11
PASSIVEOBJ_SUB_STATE_2         <- 12
PASSIVEOBJ_SUB_STATE_3         <- 13
PASSIVEOBJ_SUB_STATE_4         <- 14
PASSIVEOBJ_SUB_STATE_5         <- 15
PASSIVEOBJ_SUB_STATE_6         <- 16
PASSIVEOBJ_SUB_STATE_7         <- 17
PASSIVEOBJ_SUB_STATE_8         <- 18
PASSIVEOBJ_SUB_STATE_9         <- 19
PASSIVEOBJ_SUB_STATE_10         <- 20
 


 
 
 

 


 
 
 

 
