// �̰��� ���ļҽ��� ���� ���� ��ũ��Ʈ�θ� �����ϸ鼭 �ʿ��� ��ų���߿� �ʿ��� ���,enum �߰����� �����ϴ� �κ��Դϴ�.
// ���ļҽ��� �ִ� ���� �̰��� �����ø� �ȵ˴ϴ�.

STATE_BURSTER				<- 100	// ���뽺ų state ������

// ���� skill���� �κ��Դϴ�.
// 198	`ATMage/Buster.skl`				// ������
SKILL_BURSTER				<- 198	// ���뽺ų ������

SKILL_BENYUAN               <- 199
APID_BENYUAN                <- 330

VECTOR_FLAG_0	<- 0
VECTOR_FLAG_1	<- 1
VECTOR_FLAG_2	<- 2
VECTOR_FLAG_3	<- 3
VECTOR_FLAG_4	<- 4
VECTOR_FLAG_5	<- 5

SKL_STATIC_INT_IDX_0	<- 0
SKL_STATIC_INT_IDX_1	<- 1
SKL_STATIC_INT_IDX_2	<- 2
SKL_STATIC_INT_IDX_3	<- 3
SKL_STATIC_INT_IDX_4	<- 4
SKL_STATIC_INT_IDX_5	<- 5
SKL_STATIC_INT_IDX_6	<- 6
SKL_STATIC_INT_IDX_7	<- 7
SKL_STATIC_INT_IDX_8	<- 8

SKL_LVL_COLUMN_IDX_0	<- 0
SKL_LVL_COLUMN_IDX_1	<- 1
SKL_LVL_COLUMN_IDX_2	<- 2
SKL_LVL_COLUMN_IDX_3	<- 3
SKL_LVL_COLUMN_IDX_4	<- 4
SKL_LVL_COLUMN_IDX_5	<- 5
SKL_LVL_COLUMN_IDX_6	<- 6

PASSIVEOBJ_SUB_STATE_0	<- 10
PASSIVEOBJ_SUB_STATE_1	<- 11
PASSIVEOBJ_SUB_STATE_2	<- 12
PASSIVEOBJ_SUB_STATE_3	<- 13
PASSIVEOBJ_SUB_STATE_4	<- 14
PASSIVEOBJ_SUB_STATE_5	<- 15
PASSIVEOBJ_SUB_STATE_6	<- 16
PASSIVEOBJ_SUB_STATE_7	<- 17

BROKENARROW_UNIQUE_ID <- 9001



VECTOR_I_STATE					<- 0
VECTOR_I_FLAG					<- 1
VECTOR_I_REBIRTH_STATE			<- 2
VECTOR_I_REBIRTH_TIME			<- 3


GHOST_TIME <- 2000
ANGEL_DOWN_TIME <- 1000
DOWN_PAUSE_TIME <- 100






