
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


 
 
 
STATE_GUNNER_MSC7         <- 232    
STATE_GUNNER_SEISMICWAVE       <- 233    
STATE_GUNNER_PLASMABOOST       <- 234    
STATE_GUNNER_BURSTERBEAMNEW      <- 235    
STATE_GUNNER_DEADLYAPPROACH      <- 236    
STATE_GUNNER_WIPEOUT        <- 237    
STATE_GUNNER_SUPPRESSINGFIRE      <- 238    
STATE_GUNNER_FASTDRAW        <- 239    
STATE_GUNNER_SEVENTHFLOW       <- 240    
STATE_GUNNER_PISTOLCARBINE       <- 241    
STATE_GUNNER_GRAVITYGRENADE      <- 242    
STATE_GUNNER_DANGERCLOSE       <- 243    
STATE_GUNNER_G38ARG        <- 244    
STATE_GUNNER_SUPERNOVA        <- 245    
STATE_GUNNER_DIMENSIONRUNNER      <- 246    
STATE_GUNNER_HELLMARCH        <- 247    
STATE_CROSSBOWMASTERY				<- 95

SKILL_ZHAN_DI_GONG_XUN 					<- 135		
SKILL_BAO_TOU_ZHANG_WO 					<- 136		
SKILL_ZUO_LUN_AO_YI 					<- 137		
SKILL_GUNSTYLE    			  			<- 248

SKILL_GUNNER_MSC7         <- 232    
SKILL_GUNNER_SEISMICWAVE       <- 233    
SKILL_GUNNER_PLASMABOOST       <- 234    
SKILL_GUNNER_BURSTERBEAMNEW      <- 235    
SKILL_GUNNER_DEADLYAPPROACH      <- 236    
SKILL_GUNNER_WIPEOUT        <- 237    
SKILL_GUNNER_SUPPRESSINGFIRE      <- 238    
SKILL_GUNNER_FASTDRAW        <- 239    
SKILL_GUNNER_SEVENTHFLOW       <- 240    
SKILL_GUNNER_PISTOLCARBINE       <- 241    
SKILL_GUNNER_GRAVITYGRENADE      <- 242    
SKILL_GUNNER_DANGERCLOSE       <- 243    
SKILL_GUNNER_G38ARG        <- 244    
SKILL_GUNNER_SUPERNOVA        <- 245    
SKILL_GUNNER_DIMENSIONRUNNER      <- 246    
SKILL_GUNNER_HELLMARCH        <- 247    
SKILL_GUNNER_STYLISH      <- 248    
SKILL_GUNNER_HUASHI  <- 253
SKILL_GUNNER_COMMINTERRUPT      <- 254
SKILL_CROSSBOWMASTERY				<- 249

 
 
CUSTOM_ANI_GUNNER_MSC7MOTIONA_BODY     <- 103   
CUSTOM_ANI_GUNNER_MSC7MOTIONB_BODY     <- 104   
CUSTOM_ANI_GUNNER_SEISMICWAVECASTING    <- 105   
CUSTOM_ANI_GUNNER_SEISMICWAVECASTINGFINISH   <- 106   
CUSTOM_ANI_GUNNER_PLASMABOOSTSTART_BODY   <- 107   
CUSTOM_ANI_GUNNER_PLASMABOOSTLOOP_BODY    <- 108   
CUSTOM_ANI_GUNNER_PLASMABOOSTEND_BODY    <- 109   
CUSTOM_ANI_GUNNER_BB2NDREADY_BODY     <- 110   
CUSTOM_ANI_GUNNER_BB2NDATKA_BODY     <- 111   
CUSTOM_ANI_GUNNER_BB2NDATKB_BODY     <- 112   
CUSTOM_ANI_GUNNER_BB3RDATTACTEND_BODY    <- 113   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_START_BODY  <- 114   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_AIR_BODY   <- 115   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_FALL_BODY   <- 116   
CUSTOM_ANI_GUNNER_DEADLYAPPROACH_END_BODY   <- 117   
CUSTOM_ANI_GUNNER_WIPEOUTBODY_BODY     <- 118   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_START_BODY  <- 119   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_LOOP_BODY  <- 120   
CUSTOM_ANI_GUNNER_SUPPRESSINGFIRE_FINISH_BODY  <- 121   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSTART  <- 122   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDTURN  <- 123   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSHOT  <- 124   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDEND  <- 125   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDTRUN  <- 126   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDSHOT  <- 127   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDEND  <- 128   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSTART_LOW <- 129   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDTURN_LOW <- 130   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDSHOT_LOW <- 131   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_LEFTHANDEND_LOW <- 132   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDTRUN_LOW <- 133   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDSHOT_LOW <- 134   
CUSTOM_ANI_GUNNER_FASTDRAW_BODY_RIGHTHANDEND_LOW <- 135   
CUSTOM_ANI_GUNNER_SEVENTHFLOW1DASH     <- 136   
CUSTOM_ANI_GUNNER_SEVENTHFLOW1SHOOT    <- 137   
CUSTOM_ANI_GUNNER_SEVENTHFLOW2DASH     <- 138   
CUSTOM_ANI_GUNNER_SEVENTHFLOW2SHOOT    <- 139   
CUSTOM_ANI_GUNNER_SEVENTHFLOW3DASH     <- 140   
CUSTOM_ANI_GUNNER_SEVENTHFLOW3SHOOT    <- 141   
CUSTOM_ANI_GUNNER_SEVENTHFLOW4DASH     <- 142   
CUSTOM_ANI_GUNNER_SEVENTHFLOW4SHOOT    <- 143   
CUSTOM_ANI_GUNNER_SEVENTHFLOW5DASH     <- 144   
CUSTOM_ANI_GUNNER_SEVENTHFLOW5SHOOT    <- 145   
CUSTOM_ANI_GUNNER_SEVENTHFLOW6DASH     <- 146   
CUSTOM_ANI_GUNNER_SEVENTHFLOW6SHOOT    <- 147   
CUSTOM_ANI_GUNNER_SEVENTHFLOWLAST     <- 148   
CUSTOM_ANI_GUNNER_SEVENTHFLOWCAST     <- 149   
CUSTOM_ANI_GUNNER_PISTOLCARBINESTART_BODY   <- 150   
CUSTOM_ANI_GUNNER_PISTOLCARBINELOOP_BODY   <- 151   
CUSTOM_ANI_GUNNER_PISTOLCARBINEEND_BODY   <- 152   
CUSTOM_ANI_GUNNER_GRENADEGRAVITY_BODY    <- 153   
CUSTOM_ANI_GUNNER_DANGERCLOSE      <- 154   
CUSTOM_ANI_GUNNER_SUPERNOVA      <- 155   
CUSTOM_ANI_GUNNER_DIMENSIONRUNNERCAST    <- 156   
CUSTOM_ANI_GUNNER_HELLMARCH      <- 157   



 
 
CUSTOM_ATTACK_GUNNER_BURSTERBEAMFINISHMULTIHIT  <- 27    
CUSTOM_ATTACK_GUNNER_SUPPRESSINGFIRELOOPATTACK  <- 28    
CUSTOM_ATTACK_GUNNER_SUPPRESSINGFINISHFIRE   <- 29    
CUSTOM_ATTACK_GUNNER_FASTDRAWBODYATTACK   <- 30    


 


 
 
PASSIVEOBJ_SUB_STATE_0 <- 10
PASSIVEOBJ_SUB_STATE_1 <- 11
PASSIVEOBJ_SUB_STATE_2 <- 12
PASSIVEOBJ_SUB_STATE_3 <- 13
PASSIVEOBJ_SUB_STATE_4 <- 14
PASSIVEOBJ_SUB_STATE_5 <- 15
PASSIVEOBJ_SUB_STATE_6 <- 16
PASSIVEOBJ_SUB_STATE_7 <- 17
PASSIVEOBJ_SUB_STATE_8 <- 18
PASSIVEOBJ_SUB_STATE_9 <- 19
 


 
 
 
 