
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C

SKILL_SHI_SHEN_ZHI_LI				<- 9
SKILL_ZHENG_YI_QIAN_NENG			<- 12

SKILL_GATLING_PUNCH				<- 170
STATE_GATLING_PUNCH				<- 170

STATE_CORKSCREWBLOW				<- 171	
SKILL_CORKSCREWBLOW				<- 171	

CUSTOM_ATTACK_INFO_CORKSCREWBLOWATTACK					<- 143	
CUSTOM_ATTACK_INFO_CORKSCREWBLOWFINISH					<- 144	
 
 
STATE_PRIEST_DESTROYSPIRITTALISMAN      <- 237    
STATE_PRIEST_PENTAGON         <- 238    
STATE_PRIEST_THEBEST7HIT        <- 239    
STATE_PRIEST_DANGEROUSSCALE        <- 240    
STATE_PRIEST_ADVANCEDDRAGON        <- 241    
STATE_PRIEST_NUCLEARPUNCH        <- 242    
STATE_PRIEST_DEMOLITIONPUNCH       <- 243    
STATE_PRIEST_ATOMICCHOPPER        <- 244    
STATE_PRIEST_WRATHOFGOD         <- 245    
STATE_PRIEST_HAPTISM         <- 246    
STATE_PRIEST_MIRACLESPLITER        <- 247    
STATE_PRIEST_HOLLYSANCTUARY        <- 248    
STATE_PRIEST_SPEAROFDESTINY        <- 249    
STATE_PRIEST_JUPITER         <- 250    
STATE_PRIEST_DIVINEPUNISHMENT       <- 251    
STATE_PRIEST_DEVILFIST         <- 135    
STATE_PRIEST_DARKHOWLING        <- 136    
STATE_PRIEST_DOOMCRUSH         <- 137    
STATE_PRIEST_UNHOLYFURY         <- 138    
STATE_PRIEST_METAMORPHOSIS        <- 139    
STATE_PRIEST_INVITEOFDEVIL        <- 132    



 
 
SKILL_PRIEST_DESTROYSPIRITTALISMAN      <- 237    
SKILL_PRIEST_PENTAGON         <- 238    
SKILL_PRIEST_THEBEST7HIT        <- 239    
SKILL_PRIEST_DANGEROUSSCALE        <- 240    
SKILL_PRIEST_ADVANCEDDRAGON        <- 241    
SKILL_PRIEST_NUCLEARPUNCH        <- 242    
SKILL_PRIEST_DEMOLITIONPUNCH       <- 243    
SKILL_PRIEST_ATOMICCHOPPER        <- 244    
SKILL_PRIEST_WRATHOFGOD         <- 245    
SKILL_PRIEST_HAPTISM         <- 246    
SKILL_PRIEST_MIRACLESPLITER        <- 247    
SKILL_PRIEST_HOLLYSANCTUARY        <- 248    
SKILL_PRIEST_SPEAROFDESTINY        <- 249    
SKILL_PRIEST_JUPITER         <- 250    
SKILL_PRIEST_DIVINEPUNISHMENT       <- 251    
SKILL_PRIEST_DEVILFIST         <- 135    
SKILL_PRIEST_DARKHOWLING        <- 136    
SKILL_PRIEST_DOOMCRUSH         <- 137    
SKILL_PRIEST_UNHOLYFURY         <- 138    
SKILL_PRIEST_METAMORPHOSIS        <- 139    
SKILL_PRIEST_INVITEOFDEVIL        <- 132    
SKILL_PRIEST_COMMINTERRUPT      <- 254

 
 
CUSTOM_ANI_PRIEST_DESTROYSPIRITTALISMAN        <- 122    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK1BODY        <- 123    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK2BODY_01       <- 124    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK3BODY_01       <- 125    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK4BODY        <- 126    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK5BODY        <- 127    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK6BODY        <- 128    
CUSTOM_ANI_PRIEST_THEBEST7HIT_ATK7BODY_BODY       <- 129    
CUSTOM_ANI_PRIEST_DANGEROUSSCALE01_BODY        <- 130    
CUSTOM_ANI_PRIEST_DANGEROUSSCALE02_BODY        <- 131    
CUSTOM_ANI_PRIEST_DANGEROUSSCALE03_BODY        <- 132    
CUSTOM_ANI_PRIEST_ADVANCEDDRAGON_BRIGHT_BODY      <- 133    
CUSTOM_ANI_PRIEST_ADVANCEDDRAGON_PASSION_ATTACK      <- 134    
CUSTOM_ANI_PRIEST_NUCLEARPUNCH_CHARGE_BODY       <- 135    
CUSTOM_ANI_PRIEST_NUCLEARPUNCH_TRY_BODY        <- 136    
CUSTOM_ANI_PRIEST_NUCLEARPUNCH_ATTACK_BODY       <- 137    
CUSTOM_ANI_PRIEST_NUCLEARPUNCH_ATTACKFAILED_BODY     <- 138    
CUSTOM_ANI_PRIEST_DEMOLITIONPUNCH_A_BODY       <- 139    
CUSTOM_ANI_PRIEST_DEMOLITIONPUNCH_B_BODY       <- 140    
CUSTOM_ANI_PRIEST_ATOMICCHOPPER_READY_BODY       <- 141    
CUSTOM_ANI_PRIEST_ATOMICCHOPPER_1HIT_BODY       <- 142    
CUSTOM_ANI_PRIEST_ATOMICCHOPPER_2HIT_BODY       <- 143    
CUSTOM_ANI_PRIEST_WOGREADYBODY          <- 144    
CUSTOM_ANI_PRIEST_WOGDUCKINGEFF_BODY        <- 145    
CUSTOM_ANI_PRIEST_WOGATKA_ATK_A          <- 146    
CUSTOM_ANI_PRIEST_WOGATKB_ATK_B          <- 147    
CUSTOM_ANI_PRIEST_WOGATKC_ATK_C          <- 148    
CUSTOM_ANI_PRIEST_WOGATKD_ATK_D          <- 149    
CUSTOM_ANI_PRIEST_WOGATKE_ATK_E          <- 150    
CUSTOM_ANI_PRIEST_WOGATKF_ATK_F          <- 151    
CUSTOM_ANI_PRIEST_WOGATKG_ATK_G          <- 152    
CUSTOM_ANI_PRIEST_WOGATKH_BODY          <- 153    
CUSTOM_ANI_PRIEST_WOGATKFINISHA_BODY        <- 154    
CUSTOM_ANI_PRIEST_WOGATKFINISHB_BODY        <- 155    
CUSTOM_ANI_PRIEST_WOGATKFINISHD_BODY        <- 156    
CUSTOM_ANI_PRIEST_WOGATKFINISHE_BODY        <- 157    
CUSTOM_ANI_PRIEST_WOGFINISHATKA_BODY        <- 158    
CUSTOM_ANI_PRIEST_WOGFINISHATKB_BODY        <- 159    
CUSTOM_ANI_PRIEST_WOGFINISHATKC_BODY        <- 160    
CUSTOM_ANI_PRIEST_WOGFINISHDUCKING         <- 161    
CUSTOM_ANI_PRIEST_MSDASH_BODY          <- 162    
CUSTOM_ANI_PRIEST_MSATK_BODY          <- 163    
CUSTOM_ANI_PRIEST_MSDASHHAMMER_BODY         <- 164    
CUSTOM_ANI_PRIEST_MSATKHAMMER_BODY         <- 165    
CUSTOM_ANI_PRIEST_HOLLYSANCTUARYCAST1        <- 166    
CUSTOM_ANI_PRIEST_HOLLYSANCTUARYCAST2        <- 167    
CUSTOM_ANI_PRIEST_SPEAROFDESTINY_CAST_BODY       <- 168    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_STAY       <- 169    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_MOVE       <- 170    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SIT       <- 171    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DAMAGE1      <- 172    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DAMAGE2      <- 173    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DOWN       <- 174    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_OVERTURN      <- 175    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_JUMP       <- 176    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_REST       <- 177    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_THROW1      <- 178    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_PRAY1       <- 179    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DELIVER1      <- 180    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_BLAST1      <- 181    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_THROW2      <- 182    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_PRAY2       <- 183    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DELIVER2      <- 184    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_BLAST2      <- 185    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DASH       <- 186    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_GETITEM      <- 187    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_BUFF       <- 188    
CUSTOM_ANI_PRIEST_JUPITERNORMALATKA_BODY       <- 189    
CUSTOM_ANI_PRIEST_JUPITERNORMALATKB_BODY       <- 190    
CUSTOM_ANI_PRIEST_JUPITERNORMALATKC_BODY       <- 191    
CUSTOM_ANI_PRIEST_JUPITERHAMMERJUMPATK_BODY       <- 192    
CUSTOM_ANI_PRIEST_JUPITERHAMMERDASHATK_BODY       <- 193    
CUSTOM_ANI_PRIEST_JUPITERHAMMERUPPER_BODY       <- 194    
CUSTOM_ANI_PRIEST_JUPITERHAMMERQUAKEAREA_BODY      <- 195    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HOLLYSANCTUARYCAST1   <- 196    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HOLLYSANCTUARYCAST2   <- 197    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SPEAROFDESTINY_CAST_BODY  <- 198    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SMASHERTRYGRAB    <- 199    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SMASHERSUCCESSGRAB   <- 200    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SMASHERDASH     <- 201    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_LUCKYSTRAIGHT     <- 202    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SECONDUPPER     <- 203    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_BLADEOFPUREWHITE    <- 204    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SPEAROFVICTORYREADY   <- 205    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_SPEAROFVICTORYTHROW   <- 206    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DEFLECTWALL     <- 207    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HEALWINDCAST     <- 208    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HEALWINDBLAST     <- 209    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_APOCALYPSE     <- 210    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTCAST        <- 211    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTREADY        <- 212    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTSTART        <- 213    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTLOOP        <- 214    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTLOOPEND       <- 215    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTFINISH       <- 216    
CUSTOM_ANI_PRIEST_HAPTISM_CAST1_BODY        <- 217    
CUSTOM_ANI_PRIEST_HAPTISM_CAST2_BODY        <- 218    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTCAST   <- 219    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTREADY   <- 220    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTSTART   <- 221    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTLOOP   <- 222    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTLOOPEND  <- 223    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_DIVINEPUNISHMENTFINISH  <- 224    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HAPTISM_CAST1_BODY   <- 225    
CUSTOM_ANI_PRIEST_JUPITER_QQ506807329_HAPTISM_CAST2_BODY   <- 226    
CUSTOM_ANI_PRIEST_DEVILFIST_BODY         <- 227    
CUSTOM_ANI_PRIEST_DARKHOWLINGSTART         <- 228    
CUSTOM_ANI_PRIEST_DARKHOWLINGLOOP         <- 229    
CUSTOM_ANI_PRIEST_DARKHOWLINGEND         <- 230    
CUSTOM_ANI_PRIEST_DOOMCRUSH_DASH_HUMAN_BODY       <- 231    
CUSTOM_ANI_PRIEST_DOOMCRUSH_BOOM_HUMAN_BODY       <- 232    
CUSTOM_ANI_PRIEST_UNHOLYFURYCAST         <- 233    
CUSTOM_ANI_PRIEST_UNHOLYFURYLAST         <- 234    
CUSTOM_ANI_PRIEST_METAMORPHOSISCHANGE        <- 235    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC01        <- 236    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC03        <- 237    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC04        <- 238    
CUSTOM_ANI_PRIEST_METAMORPHOSISDASH01        <- 239    
CUSTOM_ANI_PRIEST_METAMORPHOSISDASH02        <- 240    
CUSTOM_ANI_PRIEST_METAMORPHOSISJUMP         <- 241    
CUSTOM_ANI_PRIEST_METAMORPHOSISZATTACK        <- 242    
CUSTOM_ANI_PRIEST_INVITEOFDEVIL          <- 243    
CUSTOM_ANI_PRIEST_METAMORPHOSISQUAKEAREA       <- 244    
CUSTOM_ANI_PRIEST_METAMORPHOSISAWAKENINGSTART      <- 245    


CUSTOM_ANI_PRIEST_JUPITER_STAY       <- 169    
CUSTOM_ANI_PRIEST_JUPITER_MOVE       <- 170    
CUSTOM_ANI_PRIEST_JUPITER_SIT       <- 171    
CUSTOM_ANI_PRIEST_JUPITER_DAMAGE1      <- 172    
CUSTOM_ANI_PRIEST_JUPITER_DAMAGE2      <- 173    
CUSTOM_ANI_PRIEST_JUPITER_DOWN       <- 174    
CUSTOM_ANI_PRIEST_JUPITER_OVERTURN      <- 175    
CUSTOM_ANI_PRIEST_JUPITER_JUMP       <- 176    
CUSTOM_ANI_PRIEST_JUPITER_REST       <- 177    
CUSTOM_ANI_PRIEST_JUPITER_THROW1      <- 178    
CUSTOM_ANI_PRIEST_JUPITER_PRAY1       <- 179    
CUSTOM_ANI_PRIEST_JUPITER_DELIVER1      <- 180    
CUSTOM_ANI_PRIEST_JUPITER_BLAST1      <- 181    
CUSTOM_ANI_PRIEST_JUPITER_THROW2      <- 182    
CUSTOM_ANI_PRIEST_JUPITER_PRAY2       <- 183    
CUSTOM_ANI_PRIEST_JUPITER_DELIVER2      <- 184    
CUSTOM_ANI_PRIEST_JUPITER_BLAST2      <- 185    
CUSTOM_ANI_PRIEST_JUPITER_DASH       <- 186    
CUSTOM_ANI_PRIEST_JUPITER_GETITEM      <- 187    
CUSTOM_ANI_PRIEST_JUPITER_BUFF       <- 188    

CUSTOM_ANI_PRIEST_JUPITERNORMALATKA_BODY       <- 189    
CUSTOM_ANI_PRIEST_JUPITERNORMALATKB_BODY       <- 190    
CUSTOM_ANI_PRIEST_JUPITERNORMALATKC_BODY       <- 191    
CUSTOM_ANI_PRIEST_JUPITERHAMMERJUMPATK_BODY       <- 192    
CUSTOM_ANI_PRIEST_JUPITERHAMMERDASHATK_BODY       <- 193    
CUSTOM_ANI_PRIEST_JUPITERHAMMERUPPER_BODY       <- 194    
CUSTOM_ANI_PRIEST_JUPITERHAMMERQUAKEAREA_BODY      <- 195    
CUSTOM_ANI_PRIEST_JUPITER_HOLLYSANCTUARYCAST1   <- 196    
CUSTOM_ANI_PRIEST_JUPITER_HOLLYSANCTUARYCAST2   <- 197    
CUSTOM_ANI_PRIEST_JUPITER_SPEAROFDESTINY_CAST_BODY  <- 198    
CUSTOM_ANI_PRIEST_JUPITER_SMASHERTRYGRAB    <- 199    
CUSTOM_ANI_PRIEST_JUPITER_SMASHERSUCCESSGRAB   <- 200    
CUSTOM_ANI_PRIEST_JUPITER_SMASHERDASH     <- 201    
CUSTOM_ANI_PRIEST_JUPITER_LUCKYSTRAIGHT     <- 202    
CUSTOM_ANI_PRIEST_JUPITER_SECONDUPPER     <- 203    
CUSTOM_ANI_PRIEST_JUPITER_BLADEOFPUREWHITE    <- 204    
CUSTOM_ANI_PRIEST_JUPITER_SPEAROFVICTORYREADY   <- 205    
CUSTOM_ANI_PRIEST_JUPITER_SPEAROFVICTORYTHROW   <- 206    
CUSTOM_ANI_PRIEST_JUPITER_DEFLECTWALL     <- 207    
CUSTOM_ANI_PRIEST_JUPITER_HEALWINDCAST     <- 208    
CUSTOM_ANI_PRIEST_JUPITER_HEALWINDBLAST     <- 209    
CUSTOM_ANI_PRIEST_JUPITER_APOCALYPSE     <- 210    

CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTCAST        <- 211    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTREADY        <- 212    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTSTART        <- 213    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTLOOP        <- 214    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTLOOPEND       <- 215    
CUSTOM_ANI_PRIEST_DIVINEPUNISHMENTFINISH       <- 216    
CUSTOM_ANI_PRIEST_HAPTISM_CAST1_BODY        <- 217    
CUSTOM_ANI_PRIEST_HAPTISM_CAST2_BODY        <- 218    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTCAST   <- 219    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTREADY   <- 220    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTSTART   <- 221    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTLOOP   <- 222    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTLOOPEND  <- 223    
CUSTOM_ANI_PRIEST_JUPITER_DIVINEPUNISHMENTFINISH  <- 224    
CUSTOM_ANI_PRIEST_JUPITER_HAPTISM_CAST1_BODY   <- 225    
CUSTOM_ANI_PRIEST_JUPITER_HAPTISM_CAST2_BODY   <- 226    
CUSTOM_ANI_PRIEST_DEVILFIST_BODY         <- 227    
CUSTOM_ANI_PRIEST_DARKHOWLINGSTART         <- 228    
CUSTOM_ANI_PRIEST_DARKHOWLINGLOOP         <- 229    
CUSTOM_ANI_PRIEST_DARKHOWLINGEND         <- 230    
CUSTOM_ANI_PRIEST_DOOMCRUSH_DASH_HUMAN_BODY       <- 231    
CUSTOM_ANI_PRIEST_DOOMCRUSH_BOOM_HUMAN_BODY       <- 232    
CUSTOM_ANI_PRIEST_UNHOLYFURYCAST         <- 233    
CUSTOM_ANI_PRIEST_UNHOLYFURYLAST         <- 234    
CUSTOM_ANI_PRIEST_METAMORPHOSISCHANGE        <- 235    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC01        <- 236    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC03        <- 237    
CUSTOM_ANI_PRIEST_METAMORPHOSISBASIC04        <- 238    
CUSTOM_ANI_PRIEST_METAMORPHOSISDASH01        <- 239    
CUSTOM_ANI_PRIEST_METAMORPHOSISDASH02        <- 240    
CUSTOM_ANI_PRIEST_METAMORPHOSISJUMP         <- 241    
CUSTOM_ANI_PRIEST_METAMORPHOSISZATTACK        <- 242    
CUSTOM_ANI_PRIEST_INVITEOFDEVIL          <- 243    
CUSTOM_ANI_PRIEST_METAMORPHOSISQUAKEAREA       <- 244    
CUSTOM_ANI_PRIEST_METAMORPHOSISAWAKENINGSTART      <- 245    
CUSTOM_ANI_CORKSCREWBLOWREADY_BODY						<- 288
CUSTOM_ANI_CORKSCREWBLOWATTACKA_BODY					<- 289
CUSTOM_ANI_CORKSCREWBLOWATTACKB_BODY					<- 290
CUSTOM_ANI_CORKSCREWBLOWEND_BODY						<- 291
CUSTOM_ANI_GATLING_PUNCH_END							<- 292
CUSTOM_ANI_GATLING_PUNCH_LOOP							<- 293

 
 
CUSTOM_ATTACK_PRIEST_THEBEST7HIT1      <- 98    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT2      <- 99    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT3      <- 100    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT4      <- 101    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT5      <- 102    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT6      <- 103    
CUSTOM_ATTACK_PRIEST_THEBEST7HIT7      <- 104    
CUSTOM_ATTACK_PRIEST_NUCLEARPUNCHTRY     <- 105    
CUSTOM_ATTACK_PRIEST_DEMOLITIONPUNCH     <- 106    
CUSTOM_ATTACK_PRIEST_ATOMICCHOPPER1      <- 107    
CUSTOM_ATTACK_PRIEST_ATOMICCHOPPER2      <- 108    
CUSTOM_ATTACK_PRIEST_WRATHOFGODATTACK     <- 109    
CUSTOM_ATTACK_PRIEST_WRATHOFGODHOLDATTACK    <- 110    
CUSTOM_ATTACK_PRIEST_WRATHOFGODFINISHUPPER    <- 111    
CUSTOM_ATTACK_PRIEST_MIRACLESPLITERDASH     <- 112    
CUSTOM_ATTACK_PRIEST_MIRACLESPLITERATK     <- 113    
CUSTOM_ATTACK_PRIEST_SPEAROFDESTINYTHROW    <- 114    
CUSTOM_ATTACK_PRIEST_JUPITERATTACK1      <- 115    
CUSTOM_ATTACK_PRIEST_JUPITERATTACK2      <- 116    
CUSTOM_ATTACK_PRIEST_JUPITERATTACK3      <- 117    
CUSTOM_ATTACK_PRIEST_JUPITERJUMPATTACK     <- 118    
CUSTOM_ATTACK_PRIEST_JUPITERDASHATTACK     <- 119    
CUSTOM_ATTACK_PRIEST_JUPITERQUAKEATTACK     <- 120    
CUSTOM_ATTACK_PRIEST_DEVILFIST       <- 121    
CUSTOM_ATTACK_PRIEST_DEVILFISTAWAKENING     <- 122    
CUSTOM_ATTACK_PRIEST_DOOMCRUSHDASHATTACK    <- 123    
CUSTOM_ATTACK_PRIEST_UNHOLYFURYLOOP      <- 124    
CUSTOM_ATTACK_PRIEST_UNHOLYFURYFINISH     <- 125    
CUSTOM_ATTACK_PRIEST_UNHOLYFURYCASTEXP     <- 126    
CUSTOM_ATTACK_PRIEST_UNHOLYFURYCHARGESTART    <- 127    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISATTACK1_2    <- 128    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISATTACK3    <- 129    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISATTACK4    <- 130    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISJUMPATTACK   <- 131    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISDASHATTACK   <- 132    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISDASHATTACKSMASH  <- 133    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISANTIAIRUPPER   <- 134    
CUSTOM_ATTACK_PRIEST_AWAKENINGJUMPATTACK    <- 135    
CUSTOM_ATTACK_PRIEST_AWAKENINGBASEATTACK4    <- 136    
CUSTOM_ATTACK_PRIEST_HIGHSPEEDSLASHAVENGER    <- 137    
CUSTOM_ATTACK_PRIEST_HIGHSPEEDSLASHLASTAVENGER   <- 138    
CUSTOM_ATTACK_PRIEST_HEDGEHOGDEVILAVENGER    <- 139    
CUSTOM_ATTACK_PRIEST_AWAKENINGSPINNINGDEFORMATION  <- 140    
CUSTOM_ATTACK_PRIEST_AVENGERGRASPHANDOFANGER   <- 141    
CUSTOM_ATTACK_PRIEST_METAMORPHOSISQUAKEAREA    <- 142    



 


 
 
PASSIVEOBJ_SUB_STATE_0         <- 10
PASSIVEOBJ_SUB_STATE_1         <- 11
PASSIVEOBJ_SUB_STATE_2         <- 12
PASSIVEOBJ_SUB_STATE_3         <- 13
PASSIVEOBJ_SUB_STATE_4         <- 14
PASSIVEOBJ_SUB_STATE_5         <- 15
PASSIVEOBJ_SUB_STATE_6         <- 16
PASSIVEOBJ_SUB_STATE_7         <- 17
PASSIVEOBJ_SUB_STATE_8         <- 18
PASSIVEOBJ_SUB_STATE_9         <- 19
 


 
 
APID_PRIEST_JUPITER          <- 250    
APID_PRIEST_DIVINEPUNISHMENT       <- 251    
APID_PRIEST_METAMORPHOSIS        <- 139    

 


 
 
SOUND_ID_LIGH_GET_01         <- 9401    
SOUND_ID_DIVINEPUNISHMENT        <- 9402    

 
