
//�Y�T�˽檯�A��nut�ޯର���w���ݡC�u�R���w�A�t�~�ݭn�ѥ[�̥i�H�pô��
//�@�̡G�C�t60 QQ506807329   ���{NUT�s�{�g�ޯ� ����о�1500�@��C�t�~1000�ǶO��¦��j���A�`�έק� �Ҧp�G����� �]�� ���ӫ~ �˳� �ƥ� ���� NPC NPK �Ǫ� �d�� act obj  UI�е{�������A���|�i�H���{�C


 
 
 
STATE_ATGUNNER_PLASMABOOST         <- 232    
STATE_ATGUNNER_FSC_7          <- 233    
STATE_ATGUNNER_PT_15          <- 234    
STATE_ATGUNNER_OPERATIONRAZE        <- 235    
STATE_ATGUNNER_SUPPRESSINGFIRE        <- 236    
STATE_ATGUNNER_KILLPOINT         <- 237    
STATE_ATGUNNER_CHAINDEVIDER         <- 238    
STATE_ATGUNNER_BLOODNCHAIN         <- 239    
STATE_ATGUNNER_GRAVITYGRENADE        <- 240    
STATE_ATGUNNER_PISTOLCARBINE        <- 241    
STATE_ATGUNNER_OPENFIRE          <- 242    
STATE_ATGUNNER_G96THERMOBARICGRANADE      <- 243    
STATE_ATGUNNER_DDAY           <- 244    
STATE_ATGUNNER_HS12           <- 245    
STATE_ATGUNNER_G4           <- 246    
STATE_ATGUNNER_GSPFALCON         <- 247    
STATE_ATGUNNER_MAGNETICFIELD        <- 248    
STATE_ATGUNNER_MECABOLT          <- 249    



 
 
SKILL_ATGUNNER_PLASMABOOST         <- 232    
SKILL_ATGUNNER_FSC_7          <- 233    
SKILL_ATGUNNER_PT_15          <- 234    
SKILL_ATGUNNER_OPERATIONRAZE        <- 235    
SKILL_ATGUNNER_SUPPRESSINGFIRE        <- 236    
SKILL_ATGUNNER_KILLPOINT         <- 237    
SKILL_ATGUNNER_CHAINDEVIDER         <- 238    
SKILL_ATGUNNER_BLOODNCHAIN         <- 239    
SKILL_ATGUNNER_GRAVITYGRENADE        <- 240    
SKILL_ATGUNNER_PISTOLCARBINE        <- 241    
SKILL_ATGUNNER_OPENFIRE          <- 242    
SKILL_ATGUNNER_G96THERMOBARICGRANADE      <- 243    
SKILL_ATGUNNER_DDAY           <- 244    
SKILL_ATGUNNER_HS12           <- 245    
SKILL_ATGUNNER_G4           <- 246    
SKILL_ATGUNNER_GSPFALCON         <- 247    
SKILL_ATGUNNER_MAGNETICFIELD        <- 248    
SKILL_ATGUNNER_MECABOLT          <- 249    
SKILL_ATGUNNER_STYLISH          <- 250    



 
 
CUSTOM_ANI_ATGUNNER_GRENADEAIR        <- 61    

CUSTOM_ANI_ATGUNNER_PLASMABOOSTSTART_BODY     <- 103    
CUSTOM_ANI_ATGUNNER_PLASMABOOSTLOOP_BODY     <- 104    
CUSTOM_ANI_ATGUNNER_PLASMABOOSTEND_BODY      <- 105    
CUSTOM_ANI_ATGUNNER_FSCACTIONBODY_BODY      <- 106    
CUSTOM_ANI_ATGUNNER_PT_15_NORMALSHOT      <- 107    
CUSTOM_ANI_ATGUNNER_PT_15_BACKSHOT       <- 108    
CUSTOM_ANI_ATGUNNER_PT_15_JUMPSHOT       <- 109    
CUSTOM_ANI_ATGUNNER_PT_15_READY        <- 110    
CUSTOM_ANI_ATGUNNER_OPERATIONRAZE_BODYSTART     <- 111    
CUSTOM_ANI_ATGUNNER_OPERATIONRAZE_EQUIP_12     <- 112    
CUSTOM_ANI_ATGUNNER_OPERATIONRAZE_NOTWORKOPERATION_05  <- 113    
CUSTOM_ANI_ATGUNNER_OPERATIONRAZE_WORKOPERATIONBODY_05  <- 114    
CUSTOM_ANI_ATGUNNER_ATSUPPRESSINGFIRE_START_BODY   <- 115    
CUSTOM_ANI_ATGUNNER_ATSUPPRESSINGFIRE_LOOP_BODY    <- 116    
CUSTOM_ANI_ATGUNNER_ATSUPPRESSINGFIRE_FINISH_BODY   <- 117    
CUSTOM_ANI_ATGUNNER_CHAINDEVIDER01_BODY      <- 118    
CUSTOM_ANI_ATGUNNER_CHAINDEVIDER02_BODY      <- 119    
CUSTOM_ANI_ATGUNNER_CHAINDEVIDER03_BODY      <- 120    
CUSTOM_ANI_ATGUNNER_KILLPOINTREADY_BODY      <- 121    
CUSTOM_ANI_ATGUNNER_KILLPOINTFINISHD_BODY     <- 122    
CUSTOM_ANI_ATGUNNER_KILLPOINTFINISHE_BODY     <- 123    
CUSTOM_ANI_ATGUNNER_BLOODNCHAIN_BODY      <- 124    
CUSTOM_ANI_ATGUNNER_ATGRENADEGRAVITY_BODY     <- 125    
CUSTOM_ANI_ATGUNNER_ATOPENFIRECASTING_BODY     <- 126    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINESTART_BODY     <- 127    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINELOOP_BODY     <- 128    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINEEND_BODY     <- 129    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINEAIRSTART_BODY    <- 130    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINEAIRLOOP_BODY    <- 131    
CUSTOM_ANI_ATGUNNER_PISTOLCARBINEAIREND_BODY    <- 132    
CUSTOM_ANI_ATGUNNER_HS_12SCASTBODY       <- 133    
CUSTOM_ANI_ATGUNNER_HS_12STARTBODY       <- 134    
 
CUSTOM_ANI_ATGUNNER_ATMAGNETICFIELDCASTINGLOOP_12   <- 135    
CUSTOM_ANI_ATGUNNER_ATMAGNETICFIELDCASTINGEND_10   <- 136    
CUSTOM_ANI_ATGUNNER_GSPFALCONCAST_BODY      <- 137    
CUSTOM_ANI_ATGUNNER_GSPFALCONSTART_BODY      <- 138    
CUSTOM_ANI_ATGUNNER_MECABOLTCASTING_BODY     <- 139    


 
 
CUSTOM_ATTACK_ATGUNNER_SUPPRESSINGFIRELOOPATTACK   <- 26    
CUSTOM_ATTACK_ATGUNNER_SUPPRESSINGFINISHFIRE    <- 27    
CUSTOM_ATTACK_ATGUNNER_CHAINDEVIDER1      <- 28    
CUSTOM_ATTACK_ATGUNNER_CHAINDEVIDER2      <- 29    
CUSTOM_ATTACK_ATGUNNER_CHAINDEVIDER3      <- 30    
CUSTOM_ATTACK_ATGUNNER_KILLPOINTFINISH      <- 31    
CUSTOM_ATTACK_ATGUNNER_KILLPOINTFINISHLASTSHOT    <- 32    
CUSTOM_ATTACK_ATGUNNER_BLOODNCHAINHOLDATTACK    <- 33    


 


 
 
PASSIVEOBJ_SUB_STATE_0 <- 10
PASSIVEOBJ_SUB_STATE_1 <- 11
PASSIVEOBJ_SUB_STATE_2 <- 12
PASSIVEOBJ_SUB_STATE_3 <- 13
PASSIVEOBJ_SUB_STATE_4 <- 14
PASSIVEOBJ_SUB_STATE_5 <- 15
PASSIVEOBJ_SUB_STATE_6 <- 16
PASSIVEOBJ_SUB_STATE_7 <- 17
PASSIVEOBJ_SUB_STATE_8 <- 18
PASSIVEOBJ_SUB_STATE_9 <- 19
PASSIVEOBJ_SUB_STATE_10 <- 20
PASSIVEOBJ_SUB_STATE_11 <- 21
PASSIVEOBJ_SUB_STATE_12 <- 22
PASSIVEOBJ_SUB_STATE_13 <- 23
 


 
 
 

 


 
 
SOUND_ID_ATGUNNER_G4     <- 9501    

 